package com.binarray.spring.dev.springai.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.ai.openai.OpenAiChatModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Service class for interacting with the OpenAI Chat Model.
 *
 * @author Ashesh
 */
@Slf4j
@Service
public class OpenAIService {
    private final OpenAiChatModel chatModel;

    /**
     * Constructs an OpenAIService with the specified OpenAiChatModel.
     *
     * @param chatModel the OpenAiChatModel to be used for generating chat responses
     */
    @Autowired
    OpenAIService(OpenAiChatModel chatModel) {
        this.chatModel = chatModel;
    }

    /**
     * Generates a response from the OpenAI Chat Model for the given input message.
     *
     * @param message the input message to be processed by the OpenAI Chat Model
     * @return the response generated by the OpenAI Chat Model
     * @throws RuntimeException if an error occurs during the interaction with the OpenAI Chat Model
     */
    public String chat(String message) {
        PromptTemplate promptTemplate;
        String response;
        try {
            promptTemplate = new PromptTemplate(message);

            ChatResponse chatResponse = chatModel.call(promptTemplate.create());
            response = chatResponse.getResult().getOutput().getContent();
        } catch (Exception e) {
            log.error("Error in chat: {}", e.getMessage());
            throw new RuntimeException(e);
        }
        return response;
    }
}
